schemaVersion: 2.2.0
metadata:
  name: react-native-devspace-tpl
components:
  - name: container-1
    container:
      image: 'quay.io/devfile/universal-developer-image:latest'
      mountSources: true
      memoryRequest: 500Mi
      memoryLimit: 6G
      cpuRequest: 1000m
      cpuLimit: 4000m
      endpoints:
        - name: port-8080
          targetPort: 8080
          exposure: public
